extends Node3D
class_name Zone3D
## Base for every procedural HD-2D 3D zone (Balcony3D, Scriptorium3D, and Starfall to come). It
## carries the shared environment-builder toolkit — textured primitive meshes — and the "drain to
## dark" the Cold Open director triggers when the Song stops, so a concrete zone is just its own
## `_ready()` layout written on top. See docs/Building_a_3D_Zone.md for the recipe.
##
## Conventions (keep these consistent across zones so actors and the camera behave the same
## everywhere): 1 unit = 1 m; the ground is the XZ plane with Y up; **+Z points toward the default
## camera** ("front" — the establishing shot looks out over whatever sits at -Z). Environments are
## primitive meshes (BoxMesh / planes / cylinders) wearing tiling textures generated by
## tools/gen_3d_textures.py; characters and props are the existing 2D sprites as billboards.

## Where the shared texture sets live. `ART` = generated tiling textures for meshes; `PLACE` = the
## 2D placeholder PNGs reused as prop/character art.
const ART := "res://art/3d/"
const PLACE := "res://art/placeholders/"


func _tex(path: String) -> Texture2D:
	return load(path) as Texture2D


## A StandardMaterial3D for meshes: nearest-filtered so tiling textures stay crisp, optionally tiled
## (`uv_scale`) and self-lit (`emission` > 0 makes the same texture glow — city windows, lamps).
func _mat(tex: Texture2D, uv_scale := 1.0, emission := 0.0) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	if tex:
		m.albedo_texture = tex
		m.texture_filter = BaseMaterial3D.TEXTURE_FILTER_NEAREST
		m.uv1_scale = Vector3(uv_scale, uv_scale, 1.0)
	if emission > 0.0:
		m.emission_enabled = true
		m.emission_texture = tex
		m.emission = Color(1, 1, 1)
		m.emission_energy_multiplier = emission
	return m


## Add a textured box at `pos` (its centre) and return it — the workhorse for walls, floors, steps,
## masses. `name` is the child node name (handy for finding pieces later).
func _box(size: Vector3, pos: Vector3, mat: Material, name := "Box") -> MeshInstance3D:
	var mesh := BoxMesh.new()
	mesh.size = size
	var mi := MeshInstance3D.new()
	mi.name = name
	mi.mesh = mesh
	mi.position = pos
	if mat:
		mi.material_override = mat
	add_child(mi)
	return mi


## Tween every light and emissive surface this zone made down to dark — what the director calls when
## the Song stops. `stagger` delays each successive light/emissive child (capped at 1.4 s) so a large
## zone reads as an expanding ring of quiet rather than a single snap; leave it 0 for a plain fade.
## Only OmniLight3D energy and StandardMaterial3D emissive meshes are touched; unshaded sky/billboards
## and non-emissive surfaces are left alone.
func drain_to_dark(over := 2.5, stagger := 0.0) -> void:
	var tw := create_tween().set_parallel(true)
	var i := 0
	for child in get_children():
		var delay := minf(i * stagger, 1.4)
		if child is OmniLight3D:
			tw.tween_property(child, "light_energy", 0.0, over).set_delay(delay)
			i += 1
		elif child is MeshInstance3D:
			var m: Material = (child as MeshInstance3D).material_override
			if m is StandardMaterial3D and (m as StandardMaterial3D).emission_enabled:
				tw.tween_property(m, "emission_energy_multiplier", 0.0, over).set_delay(delay)
				i += 1
